### ISSUE TITLE
can't pickle instancemethod objects

### ISSUE THREAD

**Issue by vsraptor** [noteed/python-pickle#4]
Trying to save Random Forest model. (sklearn, python 2.7x)

All the ways fail :

    def save_model(self, fname):
        with open(fname,'wb') as f :
            pickle.dump(self.model, f)

    pickle: TypeError: can't pickle instancemethod objects

    joblib : PicklingError: Can't pickle <type 'instancemethod'>: it's not found as __builtin__.instancemethod

    cPickle : TypeError: can't pickle instancemethod objects

    dill : ValueError: pickle protocol must be <= 2

-----

<pre>
.......
/usr/lib/python2.7/pickle.pyc in save(self, obj)
    284         f = self.dispatch.get(t)
    285         if f:
--> 286             f(self, obj) # Call unbound method with explicit self
    287             return
    288 

/usr/lib/python2.7/pickle.pyc in save_dict(self, obj)
    653 
    654         self.memoize(obj)
--> 655         self._batch_setitems(obj.iteritems())
    656 
    657     dispatch[DictionaryType] = save_dict

/usr/lib/python2.7/pickle.pyc in _batch_setitems(self, items)
    667             for k, v in items:
    668                 save(k)
--> 669                 save(v)
    670                 write(SETITEM)
    671             return

/usr/lib/python2.7/pickle.pyc in save(self, obj)
    304             reduce = getattr(obj, "__reduce_ex__", None)
    305             if reduce:
--> 306                 rv = reduce(self.proto)
    307             else:
    308                 reduce = getattr(obj, "__reduce__", None)

/usr/lib/python2.7/copy_reg.pyc in _reduce_ex(self, proto)
     68     else:
     69         if base is self.__class__:
---> 70             raise TypeError, "can't pickle %s objects" % base.__name__
     71         state = base(self)
     72     args = (self.__class__, base, state)

TypeError: can't pickle instancemethod objects

</pre>

**Comment by noteed** [comment]
This repository is about a Haskell library. It seems your problem is about some Python code.

**Comment by vsraptor** [comment]
sorry didn't see :{  ... will close the ticket ...
